### ISSUE TITLE
Populate default values in activiti-start-form upon starting a process

### ISSUE THREAD

**Issue by cijujoseph** [Alfresco/alfresco-ng2-components#1719] opened 2017-03-11 16:50 UTC
**Type of issue:**  (check with "[x]")
```
- [ x] New feature request
- [ ] Bug  
- [ ] Support request
- [ ] Documentation
```

**New feature request:**
I want to use activiti-start-form and pass default values on load. The use cases are: Starting an activiti process with default values from another page, or cloning a new request from another old request form etc.

**Comment by DenisVuyka** [comment] 2017-03-11 16:53
@cijujoseph Form component allows passing field values for the form. You can see an example of that in this [plunk](https://embed.plnkr.co/YSLXTqb3DtMhVJSqXKkE/) (/src/app.ts)

**Comment by DenisVuyka** [comment] 2017-03-11 16:56
@cijujoseph Form component is based on `FormModel`. This class allows providing custom values together with form definition:

```ts
 constructor(json?: any, data?: FormValues, readOnly: boolean = false, protected formService?: FormService)
```

FormValues is just a dictionary of data. 
You can get more examples on that in the Healthcare app source

**Comment by DenisVuyka** [comment] 2017-03-13 18:49
closing as duplicate of #1718

**Closed by DenisVuyka** 2017-03-13 18:49 UTC
