### ISSUE TITLE
Cannot scroll large forms

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#1134] opened 2016-11-23 13:35 UTC
If a large form is attached to start event/user task can only scroll form using up and down arrows on keyboard, scrollbar within browser is disabled/not accessible.

Issue only in Firefox and Safari, this maybe browser limitation

**Comment by VitoAlbano** [comment] 2016-11-28 15:27
It seems that the problem is now fixed, could you please retest it?

**Comment by hashraf88** [comment] 2016-11-28 16:09
Relating specifically to the scroll bar within the browser itself.

**Comment by hashraf88** [comment] 2016-11-30 12:24
Fine for forms within the 'running' filter
Whe accessing a large form via the 'completed' filter within a task (form within start event or user task) the form is not displayed centrally

<img width="1421" alt="screen shot 2016-11-30 at 12 14 21" src="https://cloud.githubusercontent.com/assets/13200338/20752095/5a3f7906-b6f7-11e6-9c92-0de5c6112932.png">

**Comment by VitoAlbano** [comment] 2016-12-02 12:25
@hashraf88 Could you add more details please? i've retried and it seems fine : 

<img width="1312" alt="screen shot 2016-12-02 at 12 24 38" src="https://cloud.githubusercontent.com/assets/7974125/20833978/620623d0-b88a-11e6-8010-f3c97b5203d0.png">

**Comment by hashraf88** [comment] 2016-12-02 17:46
Firefox and Safari is where the issues are

**Closed** 2016-12-12 11:39 UTC
Labels: browser: firefox, browser: safari, bug, comp: activiti-processList
