### ISSUE TITLE
Demo shell is not working in Safari and IE11

### ISSUE THREAD

**Issue by eromano** [Alfresco/alfresco-ng2-components#1742] opened 2017-03-21 15:15 UTC
**Type of issue:**  (check with "[x]")
```
- [ ] New feature request
- [x] Bug  
- [ ] Support request
- [ ] Documentation
```
**Current behaviour:**

**Expected behavior:**

**Steps to reproduce the issue:**

**Component name and version:** 

**Browser and version:** 

 
**Node version (for build issues):**  

**New feature request:**

**Comment by pionnegru** [comment] 2017-03-24 20:54
seems to be https://github.com/Alfresco/alfresco-ng2-components/issues/1693

**Comment by magemello** [comment] 2017-03-27 09:23
closing duplicate of #1734

**Closed by magemello** 2017-03-27 09:23 UTC
Labels: bug
