### ISSUE TITLE
If error occurs when searching, error message is incorrect

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#934] opened 2016-10-27 12:56 UTC
<img width="1346" alt="screen shot 2016-10-27 at 13 53 17" src="https://cloud.githubusercontent.com/assets/13200338/19767963/38f48af8-9c4d-11e6-882a-844c951315ab.png">

**Comment by DenisVuyka** [comment] 2016-10-28 08:53
Note that there are two error messages, second one outside the popup layout (at the bottom)
<img width="519" alt="screen shot 2016-10-28 at 09 51 34" src="https://cloud.githubusercontent.com/assets/503991/19800791/53159952-9cf4-11e6-9f15-79baf6ee36cb.png">

**Comment by hashraf88** [comment] 2016-10-31 10:54
Is this because of #555 ?

**Comment by wabson** [comment] 2016-11-01 12:30
@DenisVuyka the error only appears once after the merge of #927 where this was fixed

@hashraf88 I was tempted to close this as it's captured by #555 as you say but I saw the error text is not translated in your screenshot, so perhaps we keep it open to track that if you think that's an issue.

**Comment by hashraf88** [comment] 2016-11-01 13:23
@wabson What should the translation be? Is this similar to #828 ?

**Comment by wabson** [comment] 2016-11-01 14:23
@hashraf88 It should say *An error occurred while running the search* as shown in @DenisVuyka's [comment above](https://github.com/Alfresco/alfresco-ng2-components/issues/934#issuecomment-256869839) whereas in your screenshot the raw message key *SEARCH.RESULTS.ERROR* is shown.

**Comment by hashraf88** [comment] 2016-11-01 15:40
This issue is to resolve the error message, message should be **"An error occurred while running the search"** but is **"SEARCH.RESULTS.ERROR"**
#555 is to resolve underlying issue of why error occurs when searching

**Comment by DenisVuyka** [comment] 2016-11-01 15:43
With most recent code I cannot reproduce the i18n issue (tested with Chrome, FF and Safari)

**Comment by magemello** [comment] 2016-11-01 23:39
Closing this issue, not able to follow the conversation anymore. @hashraf88 please log in separate issues any additional problem still persisting about the search.

**Closed by magemello** 2016-11-01 23:39 UTC
Labels: browser: all, bug, comp: search
