### ISSUE TITLE
Display Value for Upload does not work properly (activiti-content)

### ISSUE THREAD

**Issue by DenisVuyka** [Alfresco/alfresco-ng2-components#1674] opened 2017-02-27 20:16 UTC
**Type of issue:**  (check with "[x]")
```
- [ ] New feature request
- [x] Bug  
- [ ] Support request
- [ ] Documentation
```
**Current behaviour:**
`<activiti-content>` component does not work properly:
- `view` button emits `contentClick` that nobody listens to (gets wrapped by `display-value` widget) 
- `download` button causes authentication dialog
- internal api `sanitizeUrl` in fact does the opposite and uses insecure api (bypasses safety checks)

**Expected behavior:**

**Steps to reproduce the issue:**

**Component name and version:** 

ng2-activiti-form@1.2.0

**Browser and version:** 

all
 
**Node version (for build issues):**  

**New feature request:**

**Comment by magemello** [comment] 2017-03-27 09:31
the issue is fixed in #1679

**Closed by magemello** 2017-03-27 09:31 UTC
Labels: bug, comp: activiti/form
