### ISSUE TITLE
PDF viewer is not displayed correctly

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#836] opened 2016-10-03 09:56 UTC
Content is not displayed in middle of page and also text is overlapping 

![screen shot 2016-10-03 at 10 55 19](https://cloud.githubusercontent.com/assets/13200338/19033755/f5a2f9ae-8957-11e6-973a-883bf8c5b0dc.png)

**Comment by eromano** [comment] 2016-10-10 12:57
It's turn out that the problem is inside Angular 2. 
This is the issue https://github.com/angular/angular/issues/11972 on Angular 2. The team seems that have committed some codes to resolve the problem but is not released in the version 2.0.2 we have to continue to check if this PR will be merged https://github.com/angular/angular/compare/2.0.x

**Comment by eromano** [comment] 2016-10-10 14:21
So after futher investigation the solution is in replace host:: with :host >>> .textLayer this because pdfJs add some HTML in dynamyc way after the compiler time and this not fit with the new way to emeulate the Shadow DOM released in the Final Angular 2 release.

When some HTML is added after the compiling time the typical attribute that angular use for emulate the shadowing are not added and the CSS compiled to fit only to the tag with these attribute is not applied to these new elements.

Using the :host in combination with >>> applies the style, but at the cost of it piercing all the way down even through "child shadow trees".

Before

```css

:host  .textLayer {
    position: absolute;
}
```
After

```css
:host >>> .textLayer {
    position: absolute;
}

```

**Comment by DenisVuyka** [comment] 2016-10-10 14:23
Can you try just the MDL approach with unique css names without :host?
i.e.: `mdl-textfield__label` or  `mdl-textfield--floating-label`

**Closed** 2016-10-14 09:59 UTC
Labels: browser: all, bug, comp: viewer, in progress
