### ISSUE TITLE
Allow customisation on the NEED HELP? and REGISTER hyperlinks on login component

### ISSUE THREAD

**Issue by cijujoseph** [Alfresco/alfresco-ng2-components#1407] opened 2017-01-06 19:01 UTC
**Type of issue:**  (check with "[x]")
```
- [x ] New feature request
- [ ] Bug  
- [ ] Support request
```
**New feature request:**
Allow customisation on the NEED HELP? and REGISTER hyperlinks on login component. The features I can think of are:
ability to provide customer specific links for these.
optionally hide these links. For example: a register may not be appropriate all the time.

**Comment by magemello** [comment] 2017-01-28 13:49
duplicate of #1212

**Closed** 2017-01-28 13:49 UTC
Labels: comp: login, New Feature
