### ISSUE TITLE
Custom stencil seems broken in 3.8

### ISSUE THREAD

**Issue by uclaeamsavino** [Alfresco/alfresco-ng2-components#5678] opened 2020-05-07 00:07 UTC
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [X ] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**
Custom stencil that works with 3.6 and 3.7 does not load with 3.8

**Expected behavior:**
Custom stencil should load in the form of a search button.

**Steps to reproduce the issue:**
Upgrade to 3.8, create a new process.

**Component name and version:** 
process-services/lib/form/form.component.ts - 3.8

```
  constructor(
 ...
    private formRenderingService: FormRenderingService
  ) {
      formRenderingService.setComponentTypeResolver('crm_search_primary', () => SearchConstituentButtonComponent, true);
   }
```

Our code matches the examples: [from demo-shell](https://github.com/Alfresco/alfresco-ng2-components/blob/develop/demo-shell/src/app/components/process-service/process-service.component.ts) and [from the yo generator](https://github.com/Alfresco/generator-alfresco-adf-app/blob/development/app/templates/adf-cli-aps-template/src/app/task-details/task-details.component.ts). Once upgrading to 3.8 we get an error message in the form instead of the search button: Unknown type: crm_search_primary

UPDATE: I commented out the providers block in [process-services/lib/form/form.component.ts](https://github.com/Alfresco/alfresco-ng2-components/blob/develop/lib/process-services/src/lib/form/form.component.ts) and the problem goes away. 

```
@Component({
    selector: 'adf-form',
    templateUrl: './form.component.html',
    encapsulation: ViewEncapsulation.None,
    providers: [
        { provide: FormRenderingService, useClass: ProcessFormRenderingService }
    ]
})
```

**Comment by DenysVuika** [comment] 2020-05-07 06:13
That is correct, in 3.8.0 there are two services now to control different Form implementations (APS 1.x and Cloud): https://github.com/Alfresco/alfresco-ng2-components/pull/5601

**Comment by tdonovancsra** [comment] 2020-05-07 14:46
+1

**Comment by uclaeamsavino** [comment] 2020-05-07 14:48
Thanks for looking into this @DenysVuika. 

I updated the issue to add links to the examples we are following in demo-shell and yo generator.  I've been trying different things to see if I can find a workaround - as we'd really like to have the Checkbox bug fix which is in v 3.8. 

No luck so far but if you can tell me a workaround to change the way we use the FromRenderingService that would be very much appreciated.

**Comment by DenysVuika** [comment] 2020-05-07 14:52
Instead of the FormRenderingService, you should be using `ProcessFormRenderingService` if you are customizing APS 1.x or `CloudFormRenderingService` if you are customizing Enterprise

**Comment by uclaeamsavino** [comment] 2020-05-07 15:08
I am using ProcessFormRenderingService in my component. I still get unknown type error on my custom widget. Can you point me to a working example?

**Comment by DenysVuika** [comment] 2020-05-07 15:12
@uclaeamsavino please see the unit tests in the https://github.com/Alfresco/alfresco-ng2-components/pull/5601

**Comment by DenysVuika** [comment] 2020-05-07 15:14
@uclaeamsavino I cannot advice without having a steps to reproduce the issue you have. We have full set of tests that is green right now, sorry.

**Comment by uclaeamsavino** [comment] 2020-05-07 15:18
Youur unit tests only run on your form.component.ts, which is the compoent for <adf-form>. 

You don't have any unit tests that run on a component like [this one from your demo-shell app](https://github.com/Alfresco/alfresco-ng2-components/blob/develop/demo-shell/src/app/components/process-service/process-service.component.ts), or [this one from the yo generator](https://github.com/Alfresco/generator-alfresco-adf-app/blob/development/app/templates/adf-cli-aps-template/src/app/task-details/task-details.component.ts) - which are components that both **embed** <adf-form> in their templates. 

This is what we're doing. I've tried everything in your unit tests and nothing has worked so far. Again this all worked on 3.7 and 3.8. 

I also noticed you added taskId to the custom widget components. I tried that as well but it didn't help.

**Comment by DenysVuika** [comment] 2020-05-07 15:29
Are you using Cloud components (process-services-cloud) or APS 1.x components (process-services) ?

**Comment by uclaeamsavino** [comment] 2020-05-07 15:35
APS

**Comment by DenysVuika** [comment] 2020-05-07 15:43
It seems to be a bug with multiple instances of ProcessFormRenderingService in memory. Investigating a way to fix it.

**Comment by tdonovancsra** [comment] 2020-05-12 13:41
@DenysVuika what's the ETA for this fix?

**Comment by DenysVuika** [comment] 2020-05-12 18:16
@tdonovancsra no ETA yet, you can watch this ticket or underlying PR (linked above) for status updates

**Comment by DenysVuika** [comment] 2020-05-13 18:33
@tdonovancsra the fix was just merged, you may want to try to get the latest alphas and test if that works for you: https://github.com/Alfresco/alfresco-ng2-components/pull/5694 Ideally you should not be changing any code at all.

**Comment by uclaeamsavino** [comment] 2020-05-13 19:06
Thanks @DenysVuika - one question - how do we know what version to put in our package.json for the latest alphas? Or are we downloading this directly somehow?

**Comment by DenysVuika** [comment] 2020-05-13 19:30
You can use `latest`, `beta` or `alpha` when installing the dependencies. For example:
```
npm install -E @alfresco/adf-core@alpha
```
Do the same for other ADF libraries your app is using.

**Comment by uclaeamsavino** [comment] 2020-05-13 19:42
Thanks - so the versions should always match right?

```
    "@alfresco/adf-content-services": "3.9.0-f6801b19974329edfde79e25e4e6ee4d7c1b59a0",
    "@alfresco/adf-core": "3.9.0-f6801b19974329edfde79e25e4e6ee4d7c1b59a0",
    "@alfresco/adf-extensions": "3.9.0-f6801b19974329edfde79e25e4e6ee4d7c1b59a0",
    "@alfresco/adf-insights": "3.9.0-f6801b19974329edfde79e25e4e6ee4d7c1b59a0",
    "@alfresco/adf-process-services": "3.9.0-f6801b19974329edfde79e25e4e6ee4d7c1b59a0",
    "@alfresco/js-api": "3.9.0-f6801b19974329edfde79e25e4e6ee4d7c1b59a0",
```

**Comment by DenysVuika** [comment] 2020-05-13 19:43
Yes, most of the time the tag is the same for all libs

**Comment by uclaeamsavino** [comment] 2020-05-13 23:54
Thanks - everything seems to work!

**Closed** 2020-05-14 10:46 UTC
Labels: bug
