### ISSUE TITLE
Task List is not displaying the available data as expected 

### ISSUE THREAD

**Issue by Salaboy** [Alfresco/alfresco-ng2-components#1699] opened 2017-03-08 11:43 UTC
**Type of issue:**  (check with "[x]")
```
- [ ] New feature request
- [ x] Bug  
- [ ] Support request
- [ ] Documentation
```
**Current behaviour:**

I'm setting up a Task List component with this definition of columns:
  this.dataTasks = new ObjectDataTableAdapter(
            [],
            [
                {type: 'text', key: 'name', title: 'Task', cssClass: 'full-width name-column', sortable: true},
                {type: 'text', key: 'dueDate', title: 'Due Date', cssClass: '', sortable: true},
                {type: 'text', key: 'processDefinitionName', title: 'Process', cssClass: '', sortable: true},
                {type: 'text', key: 'assignee', title: 'Assignee', cssClass: '', sortable: true}
            ]
        );

I can see the data being retrieved from activiti.. but the data is not displayed in the UI. 

**Expected behavior:**

I would expect to see the value of the fields name, dueDate, processDefinitionName and assignee (which is an object, so I would rather do assignee.firstName +" " + assignee.lastName, any suggestion on how to do this?) 

**Steps to reproduce the issue:**

**Component name and version:** 

**Browser and version:** 

 
**Node version (for build issues):**  

**New feature request:**

**Comment by magemello** [comment] 2017-03-08 14:40
closing duplicate of #1625

**Closed** 2017-03-08 14:40 UTC
Labels: bug, comp: activiti-taskList
