### ISSUE TITLE
Thumbnail/preview of file upload is not displayed 

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#1236] opened 2016-12-13 11:57 UTC
On a completed form the thumbnail/preview of a file upload is sometimes not displayed.  

- pdf - displayed in Safari, **not in Chome or Firefox**
- docx - **not displayed in any browser** 
- rtf - **not displayed in any browser** 
- png - displayed in all browsers
- jpg - displayed in all browsers

**Displayed**
![screen shot 2016-12-13 at 11 23 03](https://cloud.githubusercontent.com/assets/13200338/21138590/a872c5b8-c126-11e6-8153-5ca78689abac.png)

**Not displayed**
<img width="466" alt="screen shot 2016-12-13 at 11 22 51" 
src="https://cloud.githubusercontent.com/assets/13200338/21138591/a87806ea-c126-11e6-9140-261ceb24093f.png">

**Comment by mauriziovitale** [comment] 2017-01-18 12:02
@magemello This is not a bug, this is a missing feature.

**Comment by mauriziovitale** [comment] 2017-02-07 09:45
@hashraf88 Before test it, you have to npm link the latest js-api

**Comment by hashraf88** [comment] 2017-02-27 13:15
Tried with various files and browsers and get either of the below, but not a preview.

<img width="455" alt="screen shot 2017-02-27 at 12 06 08" src="https://cloud.githubusercontent.com/assets/13200338/23362676/c05a89dc-fcee-11e6-9289-e33f62c5e5b7.png">
<img width="476" alt="screen shot 2017-02-27 at 12 06 04" src="https://cloud.githubusercontent.com/assets/13200338/23362679/c7e0cc34-fcee-11e6-8591-0fb973799785.png">

**Comment by jdosti** [comment] 2017-03-01 13:20
PDF, RTF and DOCX files are not displayed.

**.pdf**
<img width="451" alt="pdf" src="https://cloud.githubusercontent.com/assets/24432311/23461202/e30cfe7c-fe80-11e6-8177-d0b07407831f.png">

**.rtf**
<img width="423" alt="rtf" src="https://cloud.githubusercontent.com/assets/24432311/23461215/f61b9f3c-fe80-11e6-92af-3400d092f69c.png">


**.docx**
<img width="420" alt="docx" src="https://cloud.githubusercontent.com/assets/24432311/23461227/01f24996-fe81-11e6-8b07-039957673d8b.png">


Tested in all browsers (chrome, firefox, safari, edge) using also the following preconditions: 

- On a form with attach widget on a start event, user task and both.
- On a form with attach widget and tabs on a start event, user task and both.
- On a form with multiple attach widgets on a start event, user task and both.
- On a form with visibility conditions on a start event, user task and both. 

**JPG** and **PNG** are displayed fine with the above preconditions in all browsers.

**Comment by hashraf88** [comment] 2017-03-01 13:55
@mauriziovitale what file types should display a preview?

**Comment by magemello** [comment] 2017-03-01 21:12
@mauriziovitale  can we use the viewer component to show the pdf files?

**Comment by mauriziovitale** [comment] 2017-03-02 12:47
@hashraf88  You should see all the types that you can see in Activiti.
There is only one problem, the first time the credential popup appear. 
To fix it I guess we should change the activiti API in order to accept the auth ticket in the query string parameters.

**Comment by mauriziovitale** [comment] 2017-03-03 15:18
File Preview fixed with PR #1689 
Remember to link the local js api before to test it. The getThumbail API is changed.

**Comment by mauriziovitale** [comment] 2017-03-03 15:19
@magemello I'll fix the show functionality using the viewer

**Comment by hashraf88** [comment] 2017-03-03 15:33
@mauriziovitale the show funtionality can be tracked seperately in #1679 so this issue can be moved on

**Closed** 2017-03-22 10:05 UTC
Labels: browser: all, comp: activiti/form, New Feature
