### ISSUE TITLE
Access SSL Certified ACS endpoints

### ISSUE THREAD

**Issue by shahjigirp** [Alfresco/alfresco-ng2-components#6213] opened 2020-10-05 14:40 UTC
**Type of issue:**  (check with "[x]")

> - [x ] New feature request
> - [ ] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**
Setup ACS with SSL using key-store and trust-store. While giving endpoint in app.config.json as this ACS, it's giving ERR_CERT_AUTHORITY_INVALID error.

**Expected behavior:**
Should be able to call ACS which is secured with SSL using p12 certificate.

**Steps to reproduce the issue:**
Configure ACS tomcat with SSL using TS and KS. Try accessing it from ng2 app.

**Component name and version:** 
alfresco-ng2-components

**Browser and version:** 
all
 
**Node version (for build issues):**  

**New feature request:**
Configuration should be passed from app.config file to allow SSL certified ACS endpoints.

**Comment by DenysVuika** [comment] 2020-10-05 14:45
It does not look like the issue is related to an ADF (Angular) application. Have you tried researching whether this issue relates to something else, i.e. https://stackoverflow.com/questions/48737370/neterr-cert-authority-invalid-when-trying-to-locally-call-to-api#48767886

**Comment by shahjigirp** [comment] 2020-10-06 05:13
Hi @DenysVuika 

It's related to ADF. Please find detailed problem statement here.

We generated our ADF v3.8 application using yeoman generator and building application using npm run build. Hence, deployment package is being generated in dist folder.

Before build, we modify app.config.json file and put EcmHost as ACS 6.2.1 endpoints.
We put this generated package folder in tomcat/webapps folder.
On accessing it, ADF application is working fine.

Now, if our ACS is running on SSL without Certificate configuration, ADF works fine. However, when our ACS is configured with certificates, we are getting not able to access ACS from ADF application and giving certificate related issue.
 
In our setup, ACS is configured using SSL Key-store and Trust-store using configurations in server.xml of tomcat. In Share side, we are passing p12 certificate file and password in remote tag of share-config-custom.xml file and share is working fine with this.

Same way, we would like to access ACS from ADF itself. Hence, I would like to know what all configuration needed in my ADF application to get this working? How can I pass p12 certificate and password with ecmHost URL? Is it possible? What all configurations needed?

**Comment by DenysVuika** [comment] 2023-07-04 20:33
closing as this is not related to the Angular or components

**Closed by DenysVuika** 2023-07-04 20:33 UTC
Labels: New Feature
