### ISSUE TITLE
Form widget "display-value" breaks when displaying uploaded file

### ISSUE THREAD

**Issue by ohej** [Alfresco/alfresco-ng2-components#1630] opened 2017-02-14 09:35 UTC
**Type of issue:**  (check with "[x]")
```
- [ ] New feature request
- [x] Bug  
- [ ] Support request
- [ ] Documentation
```
**Current behavior:**
A process form using the "Display Value" on a attached file throws an error, leaving the entire ADF UI unresponsive. This only happens when displaying a value for attached files. Using the display value for text and numbers works as expected.

![screenshot 2017-02-13 13 30 24](https://cloud.githubusercontent.com/assets/251646/22923273/0f8e61d4-f2a1-11e6-81ce-b3f7c76f4bfe.png)

This seems to be the line causing trouble: https://github.com/Alfresco/alfresco-ng2-components/blob/master/ng2-components/ng2-activiti-form/src/components/widgets/display-value/display-value.widget.html#L76

**Expected behaviour:**
Form field to be displayed properly, also the forms engine should handle the error gracefully and display an error with the single field, not break the entire page.

**Steps to reproduce the issue:**
Create a process with a form that contains an attach file field. Next form use the `Display Value` stencil to display the value of the attached file. Verify the process works.
Render form in ADF.

Attached sample process to reproduce.
[Send package.zip](https://github.com/Alfresco/alfresco-ng2-components/files/773644/Send.package.zip)

**Component name and version:** 
ng2-activiti-form, 1.1.0

**Browser and version:** 
All. Firefox does not display the error, the page just breaks.
 
**Node version (for build issues):**  
v6.9.5

**Comment by mauriziovitale** [comment] 2017-02-14 10:21
duplicate of #1586

**Closed** 2017-02-14 10:21 UTC
Labels: bug, comp: activiti/form
