### ISSUE TITLE
No component list on devproducts.alfresco.com frontpage

### ISSUE THREAD

**Issue by skopf** [Alfresco/alfresco-ng2-components#1538] opened 2017-01-24 16:43 UTC
We propagate https://devproducts.alfresco.com/ as entry point into our documentation.

As a developer without ADF experience, I want to browse the catalog of components to find something suitable to my needs. But this page just gives me a inputbox to search for a component by name. In order to get this listing, I need to search for something like "abcd". On the search result page, I finally have the "All Components" link to get the list I was looking for.

**Comment by magemello** [comment] 2017-01-24 17:05
duplicate of #1191

**Closed by magemello** 2017-01-24 17:05 UTC
