### ISSUE TITLE
Add parameter to the login component to easily change the background image

### ISSUE THREAD

**Issue by magemello** [Alfresco/alfresco-ng2-components#407] opened 2016-07-11 14:28 UTC
example:
```html
<alfresco-login bckimg="/img/background.jpg"></alfresco-login>
```

**Comment by ohej** [comment] 2016-07-13 13:22
Being able to put in a custom logo would be a good thing as well as this is a feature we see often.

**Comment by DenisVuyka** [comment] 2016-07-18 09:32
I suggest having more meaningful attribute name, like "background-image" (similar to CSS naming)

**Comment by DenisVuyka** [comment] 2016-09-01 10:03
closing as duplicate of  #534

**Closed by DenisVuyka** 2016-09-01 10:03 UTC
Labels: New Feature
