### ISSUE TITLE
Components are not fully aware of the context path they are deployed in

### ISSUE THREAD

**Issue by john-knowles** [Alfresco/alfresco-ng2-components#1606] opened 2017-02-08 09:49 UTC
**Type of issue:**  (check with "[x]")
```
- [ ] New feature request
- [X] Bug  
- [ ] Support request
- [ ] Documentation
```
**Current behaviour:**
When an ADF application is deployed into a folder some assets fail to load.

**Expected behaviour:**
Assets are loaded from the location regardless of the application being deployed into a subfolder.

**Steps to reproduce the issue:**
Deploy app to a folder for example \TestApp001\
Run application
<img width="1085" alt="login 404" src="https://cloud.githubusercontent.com/assets/18680913/22731796/c85970f4-ede3-11e6-8a04-896f4bb27432.png">

**Component name and version:** 

**Browser and version:** 

 
**Node version (for build issues):**  

**New feature request:**

**Comment by DenisVuyka** [comment] 2017-02-08 10:34
What is meant by "deploying to a folder"? The "npm run build" script provides a ready to host/publish web site in the "dist" folder. It can be hosted with any web server or choice, and virtual path configuration for that server is part of the admin responsibility, not ADF components.

**Comment by ohej** [comment] 2017-02-08 10:48
For this concrete example: An app has been built by `npm run build`. The `dist` folder has then been wrapped into a WAR file and deployed in tomcat. The issue is that if the app is served up from another path other than the root, the assets fails to load.

For example, the app could be deployed to `/test` or `/myapp`

**Comment by DenisVuyka** [comment] 2017-02-08 10:56
@ohej Ok I see now, we need testing this scenario and at least providing some guidance. We had some paths explicitly defined in 1.0 configuration, but all that was removed in 1.1.  Webpack needs additional setup if you want static resources to be in a separate folder.

**Comment by ohej** [comment] 2017-02-08 10:58
@DenisVuyka would this be something that has to be done at build time? I imagine the components should be flexible enough to be deployed into any path?

**Comment by DenisVuyka** [comment] 2017-02-08 11:03
Yes, this is a build time configuration, mainly when we concatenate all javascript files into a single bundle they need to know where to get external content (like images, fonts, etc). By default webpack expects the root path for deployed apps, maybe we can change that. In any case it has no relation to how ADF is implemented, it's a build (bundling) configuration issue.

**Comment by DenisVuyka** [comment] 2017-02-09 20:55
StackOverflow article: http://stackoverflow.com/questions/31129631/serving-webpack-built-assets-from-a-subdirectory
WebPack documentation: http://webpack.github.io/docs/configuration.html#output-publicpath

@ohej @john-knowles subdirectory hosting is specific to end-application configuration and webpack settings and does not seem to be related to ADF, I suggest forwarding these links to corresponding people and closing this issue.

**Comment by DenisVuyka** [comment] 2017-02-13 11:08
@ohej @john-knowles Ok, after having an offline discussion I do confirm the issue. 

In order to fix it we need to review and ensure all html/css files reference corresponding resources in a relative manner, not starting with the root.

Issue example:

**Login Component**
```text
background-image: url(/../assets/images/background.svg);}
```

Image refers to `root` so when hosted within virtual directory the image won't be found.

**Comment by john-knowles** [comment] 2017-02-13 12:10
Great, thank you.

**Closed** 2017-04-05 11:10 UTC
Labels: bug
